
name: upgrade-aws-native
on:
  schedule:
  - cron: 35 4 * * 1-5
  workflow_dispatch: {}


env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    name: generate-sdk
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org
    - name: Install Yarn
      run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Preparing Git Branch
      run: >
        git config --local user.email "bot@pulumi.com"

        git config --local user.name "pulumi-bot"

        git checkout -b update-aws-native/${{ github.run_id }}-${{ github.run_number }}
    - name: Get latest version
      run: ./scripts/update-aws-native.sh
    - name: Commit changes
      run: >-
        git add examples
        git add integration
        git add package.json
        git add yarn.lock
        git add schemas

        git commit -m "Updating @pulumi/aws-native dependency" || echo "ignore commit failure, may be empty"

        git push origin update-aws-native/${{ github.run_id }}-${{ github.run_number }}
    - name: Create PR
      id: create-pr
      uses: repo-sync/pull-request@v2.6.2
      with:
        destination_branch: main
        github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
        pr_body: "*Automated PR*"
        pr_title: Automated @pulumi/aws-native upgrade
        author_name: pulumi-bot
        source_branch: update-aws-native/${{ github.run_id }}-${{ github.run_number }}
